package com.hnigrowth.outreach;

import com.hnigrowth.ai.AIService;
import com.hnigrowth.ai.model.Channel;
import com.hnigrowth.ai.model.GeneratedMessage;
import com.hnigrowth.ai.model.MessageLength;
import com.hnigrowth.ai.model.MessageStage;
import com.hnigrowth.audit.AuditAction;
import com.hnigrowth.audit.AuditService;
import com.hnigrowth.common.exception.BadRequestException;
import com.hnigrowth.common.exception.ResourceNotFoundException;
import com.hnigrowth.lead.Lead;
import com.hnigrowth.lead.LeadRepository;
import com.hnigrowth.lead.LeadService;
import com.hnigrowth.outreach.dto.BulkActionResult;
import com.hnigrowth.outreach.dto.BulkActionResult.BulkItemResult;
import com.hnigrowth.outreach.dto.EditMessageRequest;
import com.hnigrowth.provider.MessageSendResult;
import com.hnigrowth.provider.MessagingProvider;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Handles AI message generation, the RM approval workflow, and (post-approval)
 * multi-channel outreach dispatch. LinkedIn sends go through MessagingProvider
 * implementations (see LinkedInMessagingProvider); email/WhatsApp/SMS providers
 * can be added the same way without touching this class.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class MessageService {

    private final MessageRepository messageRepository;
    private final LeadRepository leadRepository;
    private final LeadService leadService;
    private final AIService aiService;
    private final AuditService auditService;
    private final List<MessagingProvider> messagingProviders;
    private final ApplicationEventPublisher eventPublisher;

    @Transactional
    public OutreachMessage generate(Long leadId, Channel channel) {
        return generate(leadId, channel, MessageStage.FIRST_MESSAGE, MessageLength.LONG);
    }

    @Transactional
    public OutreachMessage generate(Long leadId, Channel channel, MessageStage stage, MessageLength length) {
        Lead lead = leadRepository.findById(leadId)
                .orElseThrow(() -> new ResourceNotFoundException("Lead", leadId));
        MessageStage effectiveStage = stage == null ? MessageStage.FIRST_MESSAGE : stage;
        MessageLength effectiveLength = length == null ? MessageLength.LONG : length;

        GeneratedMessage draft = aiService.generateMessage(lead, channel, effectiveStage, effectiveLength);

        OutreachMessage message = OutreachMessage.builder()
                .leadId(leadId)
                .channel(channel)
                .stage(effectiveStage)
                .subject(draft.subject())
                .body(draft.body())
                .status(ApprovalStatus.PENDING_APPROVAL)
                .aiGenerated(true)
                .build();
        message = messageRepository.save(message);
        auditService.log(AuditAction.AI_PROCESSING, "OutreachMessage", message.getId(),
                "AI-generated " + channel + "/" + effectiveStage + " draft for lead " + leadId
                        + " (provider=" + aiService.activeProvider() + ")");
        return message;
    }

    /** Messages are always editable before approval. */
    @Transactional
    public OutreachMessage edit(Long id, EditMessageRequest req) {
        OutreachMessage m = find(id);
        if (m.getStatus() == ApprovalStatus.SENT) {
            throw new BadRequestException("Cannot edit a message that has already been sent");
        }
        if (req.subject() != null) m.setSubject(req.subject());
        if (req.body() != null) m.setBody(req.body());
        m.setAiGenerated(false); // human-edited
        auditService.log(AuditAction.UPDATE, "OutreachMessage", id, "RM edited message content");
        return messageRepository.save(m);
    }

    /** Regenerate a fresh AI draft in place of the current one. */
    @Transactional
    public OutreachMessage regenerate(Long id) {
        OutreachMessage m = find(id);
        if (m.getStatus() == ApprovalStatus.SENT) {
            throw new BadRequestException("Cannot regenerate a message that has already been sent");
        }
        Lead lead = leadRepository.findById(m.getLeadId())
                .orElseThrow(() -> new ResourceNotFoundException("Lead", m.getLeadId()));
        GeneratedMessage draft = aiService.generateMessage(lead, m.getChannel(), m.getStage(), MessageLength.LONG);
        m.setSubject(draft.subject());
        m.setBody(draft.body());
        m.setAiGenerated(true);
        auditService.log(AuditAction.AI_PROCESSING, "OutreachMessage", id, "Message regenerated by RM request");
        return messageRepository.save(m);
    }

    @Transactional
    public OutreachMessage approve(Long id, String approver) {
        OutreachMessage m = find(id);
        m.setStatus(ApprovalStatus.APPROVED);
        m.setApprovedBy(approver);
        auditService.log(AuditAction.APPROVAL, "OutreachMessage", id, "Approved by " + approver);
        return messageRepository.save(m);
    }

    @Transactional
    public OutreachMessage reject(Long id, String comments, String rm) {
        OutreachMessage m = find(id);
        m.setStatus(ApprovalStatus.REJECTED);
        m.setRmComments(comments);
        auditService.log(AuditAction.REJECTION, "OutreachMessage", id,
                "Rejected by " + rm + (comments == null ? "" : ": " + comments));
        return messageRepository.save(m);
    }

    /**
     * Dispatch an approved message through the matching channel provider
     * (LinkedIn today; email/WhatsApp/SMS providers plug in the same way).
     * On success, publishes MessageSentEvent so the follow-up sequence
     * (Day 2/5/9/15) is scheduled without a direct dependency here.
     */
    @Transactional
    public OutreachMessage sendApproved(Long id) {
        OutreachMessage m = find(id);
        if (m.getStatus() != ApprovalStatus.APPROVED) {
            throw new BadRequestException("Only APPROVED messages can be sent");
        }
        Lead lead = leadRepository.findById(m.getLeadId())
                .orElseThrow(() -> new ResourceNotFoundException("Lead", m.getLeadId()));

        MessagingProvider provider = messagingProviders.stream()
                .filter(p -> p.supports(m.getChannel()))
                .findFirst().orElse(null);

        if (provider == null) {
            // No provider is wired for this channel at all (e.g. SMS not yet built).
            // This is a real failure -- never fabricate a "sent" status, since that
            // would tell the RM a message went out when nothing was actually
            // dispatched.
            m.setRetryCount(m.getRetryCount() + 1);
            m.setLastError(truncateError("No messaging provider configured for channel " + m.getChannel()));
            messageRepository.save(m);
            throw new BadRequestException("No messaging provider is configured for " + m.getChannel()
                    + " -- message was NOT sent.");
        }

        MessageSendResult result = provider.send(m, lead);
        // Providers (e.g. LinkedInMessagingProvider) may update lead fields as a
        // side effect of checking prerequisites (connection status, etc.) -- persist
        // those regardless of send outcome.
        leadRepository.save(lead);

        if (result.success()) {
            m.setStatus(ApprovalStatus.SENT);
            m.setSentAt(Instant.now());
            m.setProviderMessageId(result.providerMessageId());
            auditService.log(AuditAction.OUTREACH_SENT, "OutreachMessage", id,
                    "Dispatched via " + m.getChannel() + " (" + m.getStage() + ")");

            // Sending is itself an engagement signal -- rescore so a stale ICP/intent
            // snapshot doesn't linger (e.g. connectionStatus just flipped to CONNECTED).
            rescoreAfterActivity(lead);
        } else {
            m.setRetryCount(m.getRetryCount() + 1);
            m.setLastError(truncateError(result.errorMessage()));
            auditService.log(AuditAction.OUTREACH_SENT, "OutreachMessage", id,
                    "Send FAILED via " + m.getChannel() + ": " + result.errorMessage()
                            + " (retry #" + m.getRetryCount() + ")");
            messageRepository.save(m);
            throw new BadRequestException("Message dispatch failed: " + result.errorMessage());
        }

        OutreachMessage saved = messageRepository.save(m);
        eventPublisher.publishEvent(new MessageSentEvent(saved));
        return saved;
    }

    private void rescoreAfterActivity(Lead lead) {
        try {
            leadService.rescore(lead.getId());
        } catch (Exception e) {
            log.warn("[message] rescore after send failed for lead {}: {}", lead.getId(), e.getMessage());
        }
    }

    @Transactional(readOnly = true)
    public List<OutreachMessage> pending() {
        return messageRepository.findByStatusOrderByCreatedAtDesc(ApprovalStatus.PENDING_APPROVAL);
    }

    @Transactional(readOnly = true)
    public List<OutreachMessage> approvedNotSent() {
        return messageRepository.findByStatusOrderByCreatedAtDesc(ApprovalStatus.APPROVED);
    }

    /**
     * Feature: "send a LinkedIn connection request to all leads at once with a
     * default message" -- builds one CONNECTION_REQUEST message per lead from a
     * shared template (with placeholder substitution), auto-approves it as the
     * requesting RM, and sends it immediately. Continues past individual
     * failures so one bad lead (e.g. missing providerProfileId) doesn't block
     * the rest of the batch; per-lead outcomes are returned to the caller.
     */
    @Transactional
    public BulkActionResult bulkSendConnectionRequests(List<Long> leadIds, String template, String rm) {
        List<BulkItemResult> results = new ArrayList<>();
        int succeeded = 0;
        for (Long leadId : leadIds) {
            try {
                Lead lead = leadRepository.findById(leadId)
                        .orElseThrow(() -> new ResourceNotFoundException("Lead", leadId));
                String body = renderTemplate(template, lead);

                OutreachMessage message = OutreachMessage.builder()
                        .leadId(leadId)
                        .channel(Channel.LINKEDIN)
                        .stage(MessageStage.CONNECTION_REQUEST)
                        .body(body)
                        .status(ApprovalStatus.APPROVED)
                        .approvedBy(rm)
                        .aiGenerated(false)
                        .build();
                message = messageRepository.save(message);
                auditService.log(AuditAction.APPROVAL, "OutreachMessage", message.getId(),
                        "Bulk connection request auto-approved by " + rm);

                OutreachMessage sent = sendApproved(message.getId());
                results.add(new BulkItemResult(leadId, sent.getStatus() == ApprovalStatus.SENT, null));
                if (sent.getStatus() == ApprovalStatus.SENT) succeeded++;
            } catch (Exception e) {
                log.warn("[bulk-connect] failed for lead {}: {}", leadId, e.getMessage(), e);
                results.add(new BulkItemResult(leadId, false, e.getMessage()));
            }
        }
        auditService.log(AuditAction.OUTREACH_SENT, "Lead", null,
                "Bulk connection requests: " + succeeded + "/" + leadIds.size() + " sent by " + rm);
        return new BulkActionResult(leadIds.size(), succeeded, leadIds.size() - succeeded, results);
    }

    /**
     * Feature: "send a message to everyone at once" -- sends every listed
     * message. PENDING_APPROVAL messages are auto-approved by the requesting
     * RM first (this bulk action IS the approval, since the RM explicitly
     * chose to send them); APPROVED ones are sent as-is. Continues past
     * individual failures, same reasoning as bulkSendConnectionRequests.
     */
    @Transactional
    public BulkActionResult bulkSend(List<Long> messageIds, String rm) {
        List<BulkItemResult> results = new ArrayList<>();
        int succeeded = 0;
        for (Long id : messageIds) {
            try {
                OutreachMessage m = find(id);
                if (m.getStatus() == ApprovalStatus.PENDING_APPROVAL) {
                    approve(id, rm);
                }
                OutreachMessage sent = sendApproved(id);
                results.add(new BulkItemResult(id, sent.getStatus() == ApprovalStatus.SENT, null));
                if (sent.getStatus() == ApprovalStatus.SENT) succeeded++;
            } catch (Exception e) {
                log.warn("[bulk-send] failed for message {}: {}", id, e.getMessage(), e);
                results.add(new BulkItemResult(id, false, e.getMessage()));
            }
        }
        auditService.log(AuditAction.OUTREACH_SENT, "OutreachMessage", null,
                "Bulk send: " + succeeded + "/" + messageIds.size() + " sent by " + rm);
        return new BulkActionResult(messageIds.size(), succeeded, messageIds.size() - succeeded, results);
    }

    private String renderTemplate(String template, Lead lead) {
        String t = (template == null || template.isBlank())
                ? "Hi {{firstName}}, I work with senior leaders like yourself"
                        + " on bespoke wealth strategies. Would love to connect."
                : template;
        String firstName = lead.getName() == null ? "there" : lead.getName().split(" ")[0];
        return t.replace("{{firstName}}", firstName)
                .replace("{{name}}", lead.getName() == null ? "" : lead.getName())
                .replace("{{company}}", lead.getCompany() == null ? "your organization" : lead.getCompany())
                .replace("{{designation}}", lead.getDesignation() == null ? "your role" : lead.getDesignation());
    }

    @Transactional(readOnly = true)
    public List<OutreachMessage> forLead(Long leadId) {
        return messageRepository.findByLeadIdOrderByCreatedAtDesc(leadId);
    }

    private OutreachMessage find(Long id) {
        return messageRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("OutreachMessage", id));
    }

    /**
     * Defensive cap so a runaway provider/error payload can never blow past the
     * DB column again, no matter how the column is defined. This was the root
     * cause of sends getting "stuck": the DB's last_error column was narrower
     * than the (occasionally very long, e.g. raw JSON provider error bodies)
     * text we tried to save, so the save itself threw and the request never
     * completed on the frontend.
     */
    private String truncateError(String message) {
        if (message == null) {
            return null;
        }
        int max = 4000;
        return message.length() > max ? message.substring(0, max) + "...[truncated]" : message;
    }
}
